### ISSUE TITLE
Bug with all nav bar links

### ISSUE THREAD

**Issue by ummahusla** [ummahusla/Hacker-Reader#13]
At the moment, most of the links were incorrectly used, which lead to an issue to reload the whole app on each link click. 

The solution is to replace the whole links with `react-bootstrap` and `react-router-bootstrap` components. 

In the end we should see something like this. Some styling and refactoring is required.

**Navigation.js**

```js
import React from 'react';
import { Navbar, Nav, NavItem, MenuItem, NavDropdown } from 'react-bootstrap';
import { LinkContainer } from 'react-router-bootstrap';
import './Navigation.css';

const Navigation = () => (
  <div className="container">
    <Navbar fluid fixedTop>
      <Navbar.Header>
        <Navbar.Brand>
          <i className="fa fa-hacker-news fa-lg" aria-hidden="true"></i> Hacker News Reader
        </Navbar.Brand>
      </Navbar.Header>
      <Nav>
        <LinkContainer to="/top">
          <NavItem eventKey={1}>Top</NavItem>
        </LinkContainer>
        <LinkContainer to="/new">
          <NavItem eventKey={2}>New</NavItem>
        </LinkContainer>
        <LinkContainer to="/best">
          <NavItem eventKey={3}>Best</NavItem>
        </LinkContainer>
        <LinkContainer to="/jobs">
          <NavItem eventKey={4}>Jobs</NavItem>
        </LinkContainer>
        <NavDropdown eventKey={5} title="Dropdown" id="basic-nav-dropdown">
          <MenuItem eventKey={5.1}>Action</MenuItem>
          <MenuItem eventKey={5.2}>Another action</MenuItem>
          <MenuItem eventKey={5.3}>Something else here</MenuItem>
          <MenuItem divider />
          <MenuItem eventKey={5.3}>Separated link</MenuItem>
        </NavDropdown>
      </Nav>
    </Navbar>
  </div>
);

export default Navigation;
```

**Navigation.css**
```css
.navbar-default .navbar-brand {
  color: #f39c12;
  font-weight: bold;
}

.navbar-default .navbar-brand:hover,
.navbar-default .navbar-brand:focus {
  color: #e67e22;
}

.navbar-default .navbar-nav > li > a {
  color: #34495e;
}

.navbar-default .navbar-nav > li > a:hover {
  color: #7f8c8d;
}

.navbar-default .navbar-nav > .open > a,
.navbar-default .navbar-nav > .active > a {
  background-image: none;
}

.navbar-default .navbar-nav > .active > a,
.navbar-default .navbar-nav > .active > a:hover,
.navbar-default .navbar-nav > .active > a:focus {
  color: #f39c12;
}
```
